name: Export Drawio Diagrams
run-name: Export .drawio files as SVG
on: [push,workflow_dispatch]
jobs:
  Export-Drawio-Diagrams:
    runs-on: ubuntu-latest
    steps:
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: wget --quiet https://github.com/jgraph/drawio-desktop/releases/download/v24.7.8/drawio-amd64-24.7.8.deb
      - run: sudo apt install ./drawio-amd64-24.7.8.deb
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to export your Drawio files from the runner."
      - name: Export drawio files in the current directory
        run: |
          ls *.drawio
          drawio --export --format svg .
        working-directory: ${{ github.workspace }}
      - run: echo "üçè This job's status is ${{ job.status }}."
